#! /bin/bash

if [ "$1" = "-y" -o "$1" = "--yes" ]; then
	OK_TO_UPDATE=true
else
	OK_TO_UPDATE=false
fi
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd $DIR
if [ `pwd` != $DIR ]
then
	echo "Could not change to the directory $DIR"
else
	SCRIPTS_TO_UPDATE=0
	for script in `ls src`; do
		if [ ! -x $HOME/bin/$script ];then
			if [ ${SCRIPTS_TO_UPDATE} -eq 0 ];then

				echo -e "\n+------------------------------------------------------"
				echo -e   "| The following scripts will be added to $HOME/bin "
				SCRIPTS_TO_UPDATE=`expr ${SCRIPTS_TO_UPDATE} + 1`
			fi
			echo  "| $script"
		fi
	done

	if [ ${SCRIPTS_TO_UPDATE} -eq 0 ];then
		echo -e "\n*** No scripts to update ***\n"
		for script in `ls src`; do
			if [ -x $HOME/bin/$script ]
			then
				echo "Script src/$script already in $HOME/bin"
			fi
		done
		OK_TO_UPDATE=false
	else
		if [ $OK_TO_UPDATE != true ]; then
			echo -e   "|\n| Update ${SCRIPTS_TO_UPDATE} scripts (y/N) \c"
			read ok

			if [ "$ok" == 'y' -o "$ok" == "Y" ]
			then
				OK_TO_UPDATE=true
			fi
		fi
	fi
fi

# N.B. only do this with trusted variables (i.e. set directly your script)
if $OK_TO_UPDATE ; then
	if [ ! -d $HOME/bin ]
	then
		mkdir $HOME/bin/
		echo "Created $HOME/bin - add this directory to your PATH enviroment variable  in .bashrc"
	fi

	for script in `ls src`; do
		if [ ! -x $HOME/bin/$script ]
		then
			if [ -x src/$script ]
			then
				ln -s `pwd`/src/$script $HOME/bin/
				# chmod u+x $HOME/bin/$script
				echo "Added '$script' to $HOME/bin/"
			else
				echo "Ignoring src/$script since it is not executable"
			fi
		else
			echo "Script src/$script already in $HOME/bin"
		fi
	done
fi
