#! /bin/bash
APP_DIR=$HOME/repo/dev/app
if [ "$1" = "-v" -o "$1" = "--verbose" ];then
	VERBOSE=true
fi

for app in `ls $APP_DIR`
do
    cd $APP_DIR/$app
    git remote update > /dev/null 2>&1
    git status > /tmp/app-status-$$
    branch=`grep "^On branch" /tmp/app-status-$$ | cut -c10-`
    status=`grep "^Your branch is" /tmp/app-status-$$ | cut -c15-`
    grep "^Changes" /tmp/app-status-$$ > /tmp/app-status-$$-a
    grep "^Untracked" /tmp/app-status-$$ >> /tmp/app-status-$$-a
    changes=`cat /tmp/app-status-$$-a | cut -d: -f1 | sed ':a;N;$!ba;s/\n/ and /g'`

    if [ "${VERBOSE}" ];then
		remote=`git remote -v | grep fetch | cut -d$'\t' -f2 | cut -d' ' -f1`
		echo "$app|$branch|$status|$changes|$remote" | gawk  -F \| '{ printf "%-15.15s %-20.20s %s %s (%s)\n", $1, $2, $3, $4i, $5 }'
	else
		echo "$app|$branch|$status|$changes" | gawk  -F \| '{ printf "%-15.15s %-20.20s %s %s\n", $1, $2, $3, $4 }'
	fi

done
