#!/bin/bash
if [ -z "$1" ]; then
	echo -e "\nUsage:\n"
	echo -e "\t`basename $0` <venv>\n"
	echo -e "\nWhere:\n"
	echo -e "\tvenv - is the name of the <name of virtual environment (exluding"
	echo -e "\t       the 'venv-' prefix)>\n"
	exit 1
fi

if [ "`which deactivate`" != "" ];then
	deactivate
fi

VENV="venv-$1"

if [ -d "${VENV}" ]; then
	echo "The virtual environment ${VENV} already exists"
	exit
else
	echo -e "Create virtual environment: ${VENV}"
	echo -e "---------------------------"
fi

# Ubuntu 14.04 and earlier
# pyvenv-3.4 --without-pip $VENV
# source $VENV/bin/activate
# wget https://bootstrap.pypa.io/get-pip.py
# python get-pip.py
# mv get-pip.py ~/bin/

create-dot-env

REQUIREMENTS=requirements/local.txt
if [ ! -f requirements/local.txt -a -f requirements.txt ]; then
		REQUIREMENTS=requirements.txt
fi

python3 -m venv ${VENV} && \
source ${VENV}/bin/activate && \
pip install --upgrade wheel && \
pip install --upgrade pip && \
pip install -r ${REQUIREMENTS}
pip install ipdb black

if [ $? = 0 ];then
	echo -e "\n*************************************************"
	echo -e   "* Now run cd . to activate your new environment *"
	echo -e   "*************************************************\n"
else
	echo -e "\n********************************************************************************"
	echo -e   "* An error occurred please fix this issue and recreate the virtual environment *"
	echo -e   "********************************************************************************\n"
fi

