#!/bin/bash

if [ -f /run/reboot-required ]; then
    echo "Reboot is required for the following packages:"
    [ -f /run/reboot-required.pkgs ] && cat /run/reboot-required.pkgs || echo "Not listed"
    REBOOT_NOW="x"
    while [[ ! "${REBOOT_NOW}" =~ ^(n|N|y|Y)$ ]]; do
        echo -e "Reboot now (y/n) \c"
        read REBOOT_NOW
        if [[ "${REBOOT_NOW}" =~ ^(y|Y)$ ]]; then
            sudo reboot
        fi
    done
else
    echo "No reboot required"
fi
