#! /bin/bash

if [ -z $CURRENT_PROJECT ]
then
	echo -e "The environment variable CURRENT_PROJECT is not set"
	exit
fi

BACKUP_PATH=/home/${USER}/repo/backup/postgres
DATABASE_NAME="test_${CURRENT_PROJECT}_${USER}"
if [ "$1" = "" ]
then
	echo -e "Usage:\n\t$0 <restore file name>\n"
	exit
fi

FILE_NAME=$1

if [ -f ${FILE_NAME} ]
then
	FILE_PATH=${FILE_NAME}
else 
	if [ -f ${BACKUP_PATH}/${FILE_NAME} ]
	then
		FILE_PATH=${BACKUP_PATH}/${FILE_NAME}
	fi
fi

psql -X -U postgres -c "DROP DATABASE ${DATABASE_NAME}"

psql -X -U postgres -c "CREATE DATABASE ${DATABASE_NAME} TEMPLATE=template0 ENCODING='utf-8';"

psql -X --set ON_ERROR_STOP=on -U postgres -d ${DATABASE_NAME} --file ${FILE_PATH}

psql -X -U postgres -d ${DATABASE_NAME} -c "REASSIGN OWNED BY ${CURRENT_PROJECT} TO ${USER}"
