#!/bin/bash

if [ "$(which ssh-diff)" = "" ];then
    echo "This script requires ssh-diff."
    echo "On debian based systems install using sudo apt install ssh-tools"
    exit 2
fi

OPTS=

if [ "$1" = "-w" ];then
    OPTS=$1
    shift
fi

if [ "$2" = "" ]; then
    echo -e "\nUsage: $(basename $0) [-w] <file name> <remote host>:<remote directory>\n"
    exit 2
fi

ssh-diff $OPTS $1 $2/$1

